[tool.poetry]
name = "GridPuzzle"
version = "1.0.0"
description = "Grid puzzle game inspired by The Witness."
authors = ["deadlocker8"]

[[tool.poetry.source]]
name = "TheCodeLabs"
url = "https://pypi.thecodelabs.de"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
thecodelabs-baseutils = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
