[tool.poetry]
name = "GridPuzzle"
version = "1.2.0"
description = "Grid puzzle game inspired by The Witness."
authors = ["deadlocker8"]

[[tool.poetry.source]]
name = "TheCodeLabs"
url = "https://pypi.thecodelabs.de"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
thecodelabs-baseutils = "*"
thecodelabs-flaskutils = "*"
flask = "2.3.2"
Flask-SocketIO = "5.3.4"
gevent = "22.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
